import { Router } from 'express';
import { UserRole } from '@prisma/client';
import { adminController } from '../controllers/admin.controller.js';
import { aiSecurityController } from '../controllers/ai-security.controller.js';
import { enterpriseManagementController } from '../controllers/enterprise-management.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { evidenceUpload, reportUpload } from '../middleware/upload.js';
import { validate } from '../middleware/validate.js';
import { params, requestSchemas, ticketSchemas } from '../utils/validation.js';

export const adminRoutes = Router();

adminRoutes.use(requireAuth, requireRole(UserRole.ADMIN, UserRole.SUPERADMIN, UserRole.STAFF, UserRole.ANALYST));
adminRoutes.get('/dashboard', adminController.dashboard);
adminRoutes.get('/clients', adminController.clients);
adminRoutes.get('/clients/:id', validate(params.id), adminController.clientDetail);
adminRoutes.get('/clients/:id/reports', validate(params.id), adminController.clientReports);
adminRoutes.post('/clients/:id/reports', validate(params.id), reportUpload.single('report'), adminController.uploadReport);
adminRoutes.get('/tickets', adminController.tickets);
adminRoutes.patch('/tickets/:id', validate(ticketSchemas.adminPatch), adminController.patchTicket);
adminRoutes.get('/requests', adminController.requests);
adminRoutes.patch('/requests/:id', validate(requestSchemas.adminPatch), adminController.patchRequest);
adminRoutes.get('/audit-logs', adminController.auditLogs);
adminRoutes.get('/security-events', adminController.securityEvents);
adminRoutes.get('/security-events/export.csv', adminController.securityEventsCsv);
adminRoutes.get('/attack-lab/scenarios', adminController.attackScenarios);
adminRoutes.post('/attack-lab/scenarios', adminController.createAttackScenario);
adminRoutes.patch('/attack-lab/scenarios/:id', adminController.updateAttackScenario);
adminRoutes.delete('/attack-lab/scenarios/:id', adminController.deleteAttackScenario);
adminRoutes.get('/attack-lab/runs', adminController.attackRuns);
adminRoutes.post('/attack-lab/runs', adminController.startAttackRun);
adminRoutes.get('/attack-lab/runs/:id', adminController.attackRunDetail);
adminRoutes.get('/attack-lab/analytics', adminController.attackAnalytics);
adminRoutes.post('/ai/threat-model', aiSecurityController.threatModel);
adminRoutes.post('/ai/attack-surface/analyze', aiSecurityController.attackSurface);
adminRoutes.post('/ai/test-cases/generate', aiSecurityController.testCases);
adminRoutes.post('/ai/vuln/analyze', aiSecurityController.vulnerability);
adminRoutes.post('/ai/report/generate', aiSecurityController.report);
adminRoutes.post('/scans/run', aiSecurityController.runScan);
adminRoutes.get('/scans/results', aiSecurityController.scanResults);
adminRoutes.post('/ci/security-results', aiSecurityController.ciSubmit);
adminRoutes.get('/ci/security-summary', aiSecurityController.ciSummary);
adminRoutes.get('/evidence', aiSecurityController.evidenceList);
adminRoutes.post('/evidence/upload', evidenceUpload.single('evidence'), aiSecurityController.uploadEvidence);
adminRoutes.get('/evidence/:id', aiSecurityController.evidenceDetail);
adminRoutes.get('/staff-assignments', aiSecurityController.staff);
adminRoutes.post('/staff-assignments', aiSecurityController.assignStaff);
adminRoutes.get('/management/overview', enterpriseManagementController.overview);
adminRoutes.get('/staff-directory', enterpriseManagementController.staffDirectory);
adminRoutes.post('/staff-profiles', enterpriseManagementController.upsertStaffProfile);
adminRoutes.get('/shifts', enterpriseManagementController.shifts);
adminRoutes.post('/shifts', enterpriseManagementController.createShift);
adminRoutes.get('/meetings', enterpriseManagementController.meetings);
adminRoutes.post('/meetings', enterpriseManagementController.createMeeting);
adminRoutes.get('/csr', enterpriseManagementController.csr);
adminRoutes.post('/csr', enterpriseManagementController.upsertCsr);
adminRoutes.get('/messages', enterpriseManagementController.messages);
adminRoutes.post('/messages', enterpriseManagementController.createMessage);
adminRoutes.get('/soc/incidents', enterpriseManagementController.socIncidents);
adminRoutes.post('/soc/incidents', enterpriseManagementController.createSocIncident);
adminRoutes.get('/pentests', enterpriseManagementController.pentests);
adminRoutes.post('/pentests', enterpriseManagementController.createPentest);
