import { Router } from 'express';
import { UserRole } from '@prisma/client';
import { adminController } from '../controllers/admin.controller.js';
import { aiSecurityController } from '../controllers/ai-security.controller.js';
import { enterpriseManagementController } from '../controllers/enterprise-management.controller.js';
import { featureController } from '../controllers/feature.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { requirePermission } from '../middleware/permissions.js';
import { requireClientTier } from '../middleware/tierGate.js';
import { evidenceUpload, reportUpload } from '../middleware/upload.js';
import { validate } from '../middleware/validate.js';
import { aiWorkflowSchemas, adminWorkflowSchemas, params, requestSchemas, ticketSchemas } from '../utils/validation.js';

export const adminRoutes = Router();

adminRoutes.use(requireAuth, requireRole(UserRole.ADMIN, UserRole.SUPERADMIN, UserRole.STAFF, UserRole.ANALYST, UserRole.SUPERVISOR, UserRole.AUDITOR));
adminRoutes.get('/dashboard', requirePermission('client:read'), adminController.dashboard);
adminRoutes.get('/clients', requirePermission('client:read'), adminController.clients);
adminRoutes.get('/clients/:id', requirePermission('client:read'), validate(params.id), adminController.clientDetail);
adminRoutes.get('/clients/:id/reports', requirePermission('report:read'), validate(params.id), adminController.clientReports);
adminRoutes.post('/clients/:id/reports', requirePermission('report:create'), validate(params.id), reportUpload.single('report'), adminController.uploadReport);
adminRoutes.get('/tickets', requirePermission('ticket:read'), adminController.tickets);
adminRoutes.patch('/tickets/:id', requirePermission('ticket:update'), validate(ticketSchemas.adminPatch), adminController.patchTicket);
adminRoutes.get('/requests', requirePermission('request:read'), adminController.requests);
adminRoutes.patch('/requests/:id', requirePermission('request:update'), validate(requestSchemas.adminPatch), adminController.patchRequest);
adminRoutes.get('/audit-logs', requirePermission('audit:read'), adminController.auditLogs);
adminRoutes.get('/security-events', requirePermission('security-event:read'), adminController.securityEvents);
adminRoutes.get('/security-events/export.csv', requirePermission('security-event:read'), adminController.securityEventsCsv);
adminRoutes.get('/attack-lab/scenarios', requirePermission('attack-lab:read'), adminController.attackScenarios);
adminRoutes.post('/attack-lab/scenarios', requirePermission('attack-lab:write'), adminController.createAttackScenario);
adminRoutes.patch('/attack-lab/scenarios/:id', requirePermission('attack-lab:write'), adminController.updateAttackScenario);
adminRoutes.delete('/attack-lab/scenarios/:id', requirePermission('attack-lab:write'), adminController.deleteAttackScenario);
adminRoutes.get('/attack-lab/runs', requirePermission('attack-lab:read'), adminController.attackRuns);
adminRoutes.post('/attack-lab/runs', requirePermission('attack-lab:write'), validate(aiWorkflowSchemas.attackRun), requireClientTier(['shield-ops', 'shield-enterprise']), adminController.startAttackRun);
adminRoutes.get('/attack-lab/runs/:id', requirePermission('attack-lab:read'), adminController.attackRunDetail);
adminRoutes.get('/attack-lab/analytics', requirePermission('attack-lab:read'), adminController.attackAnalytics);
adminRoutes.post('/ai/threat-model', requirePermission('ai:write'), validate(aiWorkflowSchemas.threatModel), aiSecurityController.threatModel);
adminRoutes.post('/ai/attack-surface/analyze', requirePermission('attack-surface:write'), validate(aiWorkflowSchemas.attackSurface), requireClientTier(['shield-ops', 'shield-enterprise'], { optionalClientContext: true }), aiSecurityController.attackSurface);
adminRoutes.post('/ai/test-cases/generate', requirePermission('ai:write'), validate(aiWorkflowSchemas.testCases), aiSecurityController.testCases);
adminRoutes.post('/ai/vuln/analyze', requirePermission('ai:write'), validate(aiWorkflowSchemas.vulnAnalysis), aiSecurityController.vulnerability);
adminRoutes.post('/ai/report/generate', requirePermission('ai:write'), validate(aiWorkflowSchemas.report), aiSecurityController.report);
adminRoutes.post('/scans/run', requirePermission('scan:run'), validate(aiWorkflowSchemas.scanRun), requireClientTier(['shield-ops', 'shield-enterprise'], { optionalClientContext: true }), aiSecurityController.runScan);
adminRoutes.get('/scans/results', requirePermission('scan:read'), aiSecurityController.scanResults);
adminRoutes.post('/scans/results', requirePermission('scan:ingest'), validate(aiWorkflowSchemas.scanResult), aiSecurityController.ingestScanResult);
adminRoutes.post('/ci/security-results', requirePermission('scan:ingest'), validate(aiWorkflowSchemas.ciResult), aiSecurityController.ciSubmit);
adminRoutes.get('/ci/security-summary', requirePermission('scan:read'), aiSecurityController.ciSummary);
adminRoutes.get('/evidence', requirePermission('evidence:read'), aiSecurityController.evidenceList);
adminRoutes.post('/evidence/upload', requirePermission('evidence:write'), evidenceUpload.single('evidence'), validate(aiWorkflowSchemas.evidence), aiSecurityController.uploadEvidence);
adminRoutes.get('/evidence/:id', requirePermission('evidence:read'), aiSecurityController.evidenceDetail);
adminRoutes.get('/staff-assignments', requirePermission('staff:read'), aiSecurityController.staff);
adminRoutes.post('/staff-assignments', requirePermission('staff:write'), validate(adminWorkflowSchemas.staffAssignment), aiSecurityController.assignStaff);
adminRoutes.get('/feature-flags', requirePermission('client:read'), featureController.listFlags);
adminRoutes.get('/clients/:clientCompanyId/feature-flags', requirePermission('client:read'), validate(adminWorkflowSchemas.clientFeatureFlags), featureController.listClientFlags);
adminRoutes.patch('/clients/:clientCompanyId/feature-flags/:featureFlagId', requirePermission('client:update'), validate(adminWorkflowSchemas.clientFeatureFlagUpdate), featureController.setClientFlag);
adminRoutes.get('/management/overview', requirePermission('client:read'), enterpriseManagementController.overview);
adminRoutes.get('/staff-directory', requirePermission('staff:read'), enterpriseManagementController.staffDirectory);
adminRoutes.post('/staff-profiles', requirePermission('staff:write'), validate(adminWorkflowSchemas.staffProfile), enterpriseManagementController.upsertStaffProfile);
adminRoutes.get('/shifts', requirePermission('schedule:read'), enterpriseManagementController.shifts);
adminRoutes.post('/shifts', requirePermission('schedule:write'), validate(adminWorkflowSchemas.shift), enterpriseManagementController.createShift);
adminRoutes.get('/meetings', requirePermission('meeting:read'), enterpriseManagementController.meetings);
adminRoutes.post('/meetings', requirePermission('meeting:write'), validate(adminWorkflowSchemas.meeting), enterpriseManagementController.createMeeting);
adminRoutes.get('/csr', requirePermission('crm:read'), enterpriseManagementController.csr);
adminRoutes.get('/csr/dashboard', requirePermission('crm:read'), enterpriseManagementController.csrDashboard);
adminRoutes.get('/csr/health', requirePermission('crm:read'), enterpriseManagementController.csrHealth);
adminRoutes.get('/csr/sla', requirePermission('crm:read'), enterpriseManagementController.csrSlaMetrics);
adminRoutes.get('/csr/renewals', requirePermission('crm:read'), enterpriseManagementController.csrRenewals);
adminRoutes.post('/csr', requirePermission('crm:write'), validate(adminWorkflowSchemas.csr), enterpriseManagementController.upsertCsr);
adminRoutes.get('/crm', requirePermission('crm:read'), enterpriseManagementController.csr);
adminRoutes.get('/crm/dashboard', requirePermission('crm:read'), enterpriseManagementController.csrDashboard);
adminRoutes.get('/crm/health', requirePermission('crm:read'), enterpriseManagementController.csrHealth);
adminRoutes.get('/crm/sla', requirePermission('crm:read'), enterpriseManagementController.csrSlaMetrics);
adminRoutes.get('/crm/renewals', requirePermission('crm:read'), enterpriseManagementController.csrRenewals);
adminRoutes.post('/crm', requirePermission('crm:write'), validate(adminWorkflowSchemas.csr), enterpriseManagementController.upsertCsr);
adminRoutes.get('/crm/contacts', requirePermission('crm:read'), enterpriseManagementController.crmContacts);
adminRoutes.post('/crm/contacts', requirePermission('crm:write'), validate(adminWorkflowSchemas.crmContact), enterpriseManagementController.createCrmContact);
adminRoutes.get('/crm/tasks', requirePermission('crm:read'), enterpriseManagementController.crmTasks);
adminRoutes.post('/crm/tasks', requirePermission('crm:write'), validate(adminWorkflowSchemas.crmTask), enterpriseManagementController.createCrmTask);
adminRoutes.get('/crm/lifecycle', requirePermission('crm:read'), enterpriseManagementController.crmLifecycle);
adminRoutes.post('/crm/lifecycle', requirePermission('crm:write'), validate(adminWorkflowSchemas.crmLifecycle), enterpriseManagementController.createCrmLifecycle);
adminRoutes.post('/crm/renewals', requirePermission('crm:write'), validate(adminWorkflowSchemas.renewalOpportunity), enterpriseManagementController.createRenewalOpportunity);
adminRoutes.get('/crm/timeline', requirePermission('crm:read'), enterpriseManagementController.crmTimeline);
adminRoutes.get('/messages', requirePermission('message:read'), enterpriseManagementController.messages);
adminRoutes.post('/messages', requirePermission('message:write'), validate(adminWorkflowSchemas.message), enterpriseManagementController.createMessage);
adminRoutes.get('/soc/incidents', requirePermission('soc:read'), enterpriseManagementController.socIncidents);
adminRoutes.post('/soc/incidents', requirePermission('soc:write'), validate(adminWorkflowSchemas.socIncident), enterpriseManagementController.createSocIncident);
adminRoutes.get('/pentests', requirePermission('pentest:read'), enterpriseManagementController.pentests);
adminRoutes.post('/pentests', requirePermission('pentest:write'), validate(adminWorkflowSchemas.pentest), enterpriseManagementController.createPentest);
